create table if not exists intake_submissions
(
    id bigint not null auto_increment primary key,
    submitted_at timestamp not null default current_timestamp,
    full_name varchar(100) not null,
    email_address varchar(256) not null,
    phone_number varchar(64) not null default '',
    suburb_or_area varchar(120) not null,
    project_stage varchar(120) not null,
    interested_plan varchar(120) not null,
    service_mode varchar(120) not null default '',
    service_format varchar(120) not null default '',
    room_type varchar(120) not null,
    primary_goals text not null,
    room_dimensions varchar(400) not null,
    budget_band varchar(120) not null,
    timeline varchar(120) not null,
    needs_acoustic_design tinyint(1) not null default 0,
    needs_calibration tinyint(1) not null default 0,
    needs_automation tinyint(1) not null default 0,
    needs_procurement_advice tinyint(1) not null default 0,
    needs_existing_equipment_installation tinyint(1) not null default 0,
    needs_guidance_only tinyint(1) not null default 0,
    existing_equipment text not null,
    key_challenges text not null,
    contact_preference varchar(120) not null,
    client_id bigint null,
    index ix_intake_submissions_submitted_at (submitted_at),
    index ix_intake_submissions_email_address (email_address)
);
